### ISSUE TITLE
Jake's Lorem Tools Plan

### ISSUE THREAD

**Issue by jake-nathan** [whoismattclark/lorem-tools#1]
**The Cold Approach**

Make list of 100 product managers, graphic designers and web developers and reach out to them via email about lorem. Just straight up cold emails. See if something happens. Numbers game.

**Issue That Need to be Fixed**

Lorem.tools is http not https which means chrome will deem it not secure so this needs to be fixed

**The Growth Hack**

Make an instagram and twitter with handle @loremtools (I checked, it’s available)
 
Jake and matt ask 5-10 friends to follow this account just so the numbers don’t look awful

Make list of another 25-50 product managers, graphic designers and web developers 

Reach out to them via email about asking to do a 10 minute interview with them for a new series you’re doing 

And post these interviews on instagram and twitter and encourage the interviewees to share them

Also on twitter tag people with big followings and see if they can like the tweets (if they do they will get a bunch of retweets)

**The Launch**

Launch Product on Product Hunt

Warning: 14 Lorem Ipsum-related products already launched on product hunt

Research PH launch strategies and generate a 1-2 page document (approved by matt) covering launch details

**Comment by whoismattclark** [comment]
What is the purpose of the interviews? Where will they be hosted?

**Comment by whoismattclark** [comment]
What logging/tagging do we need to know which strategy worked best?

**Comment by whoismattclark** [comment]
Are we relying 100% on direct traffic or are there things worth doing to get organic traffic?

**Comment by jake-nathan** [comment]
**What is the purpose of the interviews? Where will they be hosted?**
The purpose of these interviews is purely to try to get the people we interview to share our social media pages or website. If a random person asks you to share their product on FB, you probably would say no. But, if they interviewed you and made a video about your interview, you would be more likely to share that. It's a little bit hard to describe over text, but does that make sense? It's something that I did with my old website and got some good traffic to it immediately. As far as hosting, we could just start by posting them on lorem's social media account. Or there could be a blog section under the website but that seems like a pain. 

**What logging/tagging do we need to know which strategy worked best?**
I don't have too much experience with this so you might be able to chip in more. For me, Google Analytics was always good enough because you could see how people were getting to your site. For example, if a bunch of people were coming to the website from gmail, then that means our email campaign worked. Or if they came from Instagram or Twitter or FB, or social media has worked. Obviously not 100% accurate but that's what I do. Thoughts?

**What logging/tagging do we need to know which strategy worked best?**
To get from 0-100 visits, I feel like direct traffic will have to be what we rely on. Since you just made the website and there are dozens of lorem ipsum generators out there, I don't think we'll be able to get on the first page of google any time soon. We would need to start a blog or something to generate a way for people to come to our website organically, and it usually takes 6-8 months for most articles to rank on Google. Do you have any thoughts on how to get organic traffic?
