### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by whoismattclark** [whoismattclark/lorem-tools#2]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/119010/51815236-2946a080-2285-11e9-919b-7c0fdb3ad060.png">
Looks like I just need to click this box ☝️ 😬 .

**Comment by whoismattclark** [comment]
Did it.

**Comment by whoismattclark** [comment]
Success. http://lorem.tools redirects to https://lorem.tools.

**Comment by whoismattclark** [comment]
@jake-nathan, can you verify and close if it works for you too without any browser warnings?

**Comment by jake-nathan** [comment]
Works great!
